### ISSUE TITLE
[Bug] What's next 추천 컨텐츠 반응오류

### ISSUE THREAD

**Issue by dantwort-jihyun** [tuktak/catchupseoul#1]
**Describe the bug**
1) What's next 에 추천된 컨텐츠 썸네일 클릭 시, 해당 컨텐츠로 이동 불가
2) 동일한 썸네일 2번째 클릭 부터 클릭액션 먹히지 않음

**To Reproduce**

1. HOME에서 New 섬네일 아무거나 클릭 (spot  페이지로 이동)
2. spot 페이지 최하단의 What's next까지 이동
3. A썸네일 클릭 시 > A컨텐츠로 이동되지 않고, spot 페이지의 상단으로 이동 
4. A썸네일 2번째 클릭 시> 아무런 반응 없음

**Expected behavior**
명확하고 간결하게 어떤 형태로 동작하여야 하는지 설명해 주세요.

**Screenshots**
만약 등록가능하다면, 문제 설명을 위해 스크린샷을 첨부해 주세요.

** 아래 사항을 완성해 주세요**
- target :  Browser/ iOS App/ Android App/ CMS 미리보기에서 모두 발생
- OS & Version :  Window7 / iOS 12.1 / 
- Device:  iPhone 6s
- Browser & Version: Chrome

**Additional context**
문제에 관한 추가적인 정보가 있으면 여기에 적어 주세요.

**Comment by theodoreLee** [comment]
현재 이동 이슈 수정하여 업로드하였습니다. 해당 이슈가 다시 발생하면 코멘트 부탁드립니다.
