### ISSUE TITLE
[Bug] 이미지 주소노출 문제

### ISSUE THREAD

**Issue by plzen-dantwort** [tuktak/catchupseoul#4]
하나씩 하나씩 한글로 된 설명 부분을 지우고 작성하시면 더 편합니다.

**Describe the bug**
안드로이드에서 앱내에 이미지들을 누르고 있으면 Save Image 와 AWS 주소가 노출됨

**To Reproduce**
앱내에 모든 이미지들을 누르고 있으면  Save Image 와 AWS 주소가 노출됨

**Screenshots**

![Screenshot_2019-04-08-11-49-42](https://user-images.githubusercontent.com/46474452/55696116-82a21d00-59f6-11e9-9203-cdeaa24f1506.png)

** 아래 사항을 완성해 주세요**
- target : [Android App]
- OS & Version : [Android 8.1.0]
- Device: [LG V40]
- Browser & Version: [앱이 *아닌* 경우, e.g. safari 10]

**Additional context**

**Comment by theodoreLee** [comment]
https://play.google.com/apps/testing/com.dantwort.catchupseoul
해당 이슈 수정 버전 알파 등록하였습니다.
